on:
  pull_request:

name: Review Workflow

jobs:
  review:
    name: Review Job
    runs-on: ubuntu-latest
    steps:
      # prepare env
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.31
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      
      # library check
      - name: Install
        run: bun install
      - name: Test
        run: bun run test
      - name: Build
        run: bun run build
      - name: Lint
        run: bun run lint